spring:
  datasource:
    url: jdbc:mysql://localhost:3306/manage-material
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  thymeleaf:
    cache: false
  security:
    user:
      name: admin
      password: admin
      roles: ADMIN